inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'rails_*/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'api_error_handler.gemspec'

Style/Documentation:
  Enabled: false
