---
language: ruby
before_install:
  - gem update --system
  - gem install bundler
install: bundle install --jobs=3 --retry=3
cache: bundler
branches:
  only:
    - master
jobs:
  include:
  - rvm: 2.5.1
    gemfile: ./rails_5_test_app/Gemfile
    script: cd rails_5_test_app && bundle exec rspec
  - rvm: 2.5.1
    gemfile: ./rails_6_test_app/Gemfile
    script: cd rails_6_test_app && bundle exec rspec
  - rvm: 2.7.2
    gemfile: ./rails_6_test_app/Gemfile
    script: cd rails_6_test_app && bundle exec rspec
  - rvm: 3.0.0
    gemfile: ./rails_6_test_app/Gemfile
    script: cd rails_6_test_app && bundle exec rspec
  - rvm: 2.7.2
    gemfile: Gemfile
    script: bundle exec rubocop
  - rvm: 2.7.2
    gemfile: Gemfile
    script: bundle exec rspec
  - rvm: 3.0.0
    gemfile: Gemfile
    script: bundle exec rubocop
  - rvm: 3.0.0
    gemfile: Gemfile
    script: bundle exec rspec
